[language-server.bash-language-server]
command = "bash-language-server"
args = ["start"]

[language-server.texlab]
command = "texlab"


[language-server.ltex-ls]
command = "ltex-ls"


[language-server.nil]
command = "nil"


[language-server.rust-analyzer]
command = "rust-analyzer"

[[language]]
name = "nix"
scope = "source.nix"
formatter = { command = "alejandra", args = ["--quiet"] }
language-servers = [{ name = "nil" }]


[language-server.pylsp]
command = "pylsp"

[[ grammar ]]
name = "nix"
source = { git = "https://github.com/nix-community/tree-sitter-nix", rev = "02878b40ac77d2889833519c6b6e9e63cfc690e6" }

[[language]]
name = "bash"
scope = "source.sh"
shebangs = ["sh", "bash", "dash"]
formatter = { command = "shfmt"}
language-servers = [{ name = "bash-language-server" }]

[[language]]
name = "rust"
scope = "source.rs"
formatter = { command = "rustfmt" }
language-servers = [{ name = "rust-analyzer" }]

[[language]]
name = "latex"
file-types = ["tex"]
language-servers = [{ name = "texlab"}, { name = "ltex-ls"}]

[[language]]
name = "bibtex"
file-types = ["bib"]

[[language]]
name = "python"
file-types = ["py"]
formatter = { command = "black", args = ["-"] }
language-servers = [{ name = "pylsp" }]
